### PR TITLE
Move code of conduct to root

### LINKED ISSUE #52: Move code of conduct to a directory readable by github
https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

### PR DESCRIPTION
**Pull request by renatoruk**
- moved code of conduct from getting-started dir to root

Closes #52

### CODE REVIEW

**Comment by degdebug** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Found a new file with underscores, this repo uses kebab-case for files: CODE_OF_CONDUCT.md
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 01c647846313e5be7783b74cd044cde0e0f6d608
</p>

**Comment by tonymrakovcic** [comment]
Merge this into one with this?
https://github.com/bornfight/README/blob/master/getting-started/code-of-conduct.md

**Comment by renatoruk** [comment]
> Merge this into one with this?
> https://github.com/bornfight/README/blob/master/getting-started/code-of-conduct.md

The main motivation is to s

> Merge this into one with this?
> https://github.com/bornfight/README/blob/master/getting-started/code-of-conduct.md

It's the same one, only moved it for some automatic github detection! I only created a PR with GitHub so I can work on it from there. Still doing some adjustments for contributing so the rules are more prominent. 

Should've made a draft, you are very fast  :D

**Comment by tonymrakovcic** [comment]
Since danger.js is complaining about kebab case which is defined as a rule, and github probably needs snake case exactly for implementation, you can make an exception to the kebab case rule for this file only or something similar, here

https://github.com/bornfight/README/blob/master/dangerfile.ts#L42

**Comment by renatoruk** [comment]
> Since danger.js is complaining about kebab case which is defined as a rule, and github probably needs snake case exactly for implementation, you can make an exception to the kebab case rule for this file only or something similar, here
> 
> https://github.com/bornfight/README/blob/master/dangerfile.ts#L42

Awesome, thanks for the tip :)

**Pull request merged**
