### PR TITLE
Add kru blogs from devedu

### PR DESCRIPTION
**Pull request by krukru**
Big thanks to @tonymrakovcic who ported the blogs to markdown

### CODE REVIEW

**Comment by tonymrakovcic** [comment]
hmm, i need to check how peoples workflows work :) and how the script handles on other peoples setups.
I see the table of contents didn't update
It is implemented as a githook

manually it's `` yarn setup-structure``

**Comment by tonymrakovcic** [comment]
does it make sense to you that the structure is in playbooks and best practices instead of the educations folder?

playbooks folder:
anatomy of a deploy
running jenkins jobs

best practises folder:
executable docs
metaphors
unified code style

**Comment by tonymrakovcic** [comment]
@krukru what do you think of the folder placement I propose?
If you'rer ok with it, please just place them like that and hit `yarn setup-structure` (after `yarn install`ing)
Although after yarn install it should be a git hook

**Comment by krukru** [comment]
I agree with the proposed changes, I will find time to rearrange the files by the end of the day

**Pull request merged**
